title: Working offline Python
hero_image: images/banner.png
description: Working offline Python
version: 4
listed: false
copyedit: false
last_tested: "2021-08-02"
steps:
  - title: Working offline Python
